version: "3"

services:
    postgres:
        image: "postgres:15.5"
        restart: always
        ports:
            - "5432:5432"
        environment:
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=focus
        volumes:
            - postgres_data:/var/lib/postgresql/data
         

    pgadmin:
        image: "dpage/pgadmin4"
        restart: always
        ports:
            - "80:80"
        environment:
             PGADMIN_DEFAULT_EMAIL: "postgres@postgres.com"
             PGADMIN_DEFAULT_PASSWORD: "postgres"
        depends_on:
            - postgres
        volumes:
            - pgadmin_data:/var/lib/pgadmin 
volumes:
  postgres_data:    
  pgadmin_data: