version: "3.8"

services:
    postgres:
        image: "postgres:latest"
        restart: always
        ports:
            - "5432:5432"
        environment:
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=postgres

    pgadmin:
        image: "dpage/pgadmin4"
        restart: always
        ports:
            - "5433:5433"
        environment:
             PGADMIN_DEFAULT_EMAIL: "postgres@postgres.com"
             PGADMIN_DEFAULT_PASSWORD: "postgres"
        depends_on:
            - postgres